/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MacbookCustom.glb -T 
Files: MacbookCustom.glb [4.01MB] > /home/lea/Documentos/mariodev3d/public/models/MacbookCustom-transformed.glb [540.78KB] (87%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/MacbookCustom-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 0.31, -12.21]} rotation={[1.92, 0, 0]}>
          <mesh name="glass" geometry={nodes.glass.geometry} material={materials.sfCQkHOWyrsLmor} position={[0, 0.36, 12.49]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="stickers" geometry={nodes.stickers.geometry} material={materials.stickers} position={[0.16, 11.456, -4.779]} rotation={[1.222, 0, -Math.PI]} scale={24.224} />
          <mesh name="Tapa" geometry={nodes.Tapa.geometry} material={materials.lmWQsEjxpsebDlK} position={[0, 0.36, 12.49]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="tapa1" geometry={nodes.tapa1.geometry} material={materials.PaletteMaterial001} position={[0, 0.36, 12.49]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="tapa2" geometry={nodes.tapa2.geometry} material={materials.PaletteMaterial002} position={[0, 0.36, 12.49]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/MacbookCustom-transformed.glb')
